/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'PIKU' at '12/27/15 7:55 PM' with Gradle 2.9
 *
 * @author PIKU, @date 12/27/15 7:55 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
